In [1]:
! pip install numpy

You should consider upgrading via the 'C:\New folder\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np
np.__version__

'1.21.4'

In [27]:
## 1D
npar = np.arange(1,28,dtype=np.float64)
npar.ndim
npar.dtype
npar.shape
# npar.reshape(5,2)
npar.reshape(3,3,3).shape
npar.size
npar.itemsize

216

In [32]:
## Access
npar[2:7:2]
npar[2] = 9
npar

array([ 1.,  2.,  9.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27.])

In [38]:
## 2D
arr2d = np.array([[1,2,3],[4,5,7],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 7],
       [4, 5, 6]])

In [46]:
arr2d[0:2:2, 2]
arr2d[1, :]

array([4, 5, 7])

In [52]:
# 3D
arr3d = npar.reshape(3,3,3)
arr3d

array([[[ 1.,  2.,  9.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]]])

In [56]:
arr3d[:, 0, :]

array([[ 1.,  2.,  9.],
       [10., 11., 12.],
       [19., 20., 21.]])

In [61]:
## Function for Array
np.empty((3,3))

array([[ 1.,  2.,  9.],
       [10., 11., 12.],
       [19., 20., 21.]])

In [62]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
## Functions
npar.mean()
npar.std()
npar.var()
npar.sum()
npar.sort()
npar.max()
npar.min()

1.0

In [77]:
np.median(npar)
np.cov(npar)

array(59.25641026)

In [84]:
arr2d

array([[1, 2, 3],
       [4, 5, 7],
       [4, 5, 6]])

In [87]:
arr2d.mean(axis=0)

array([3.        , 4.        , 5.33333333])

In [89]:
arr2d.mean(axis=1)

array([2.        , 5.33333333, 5.        ])

In [90]:
arr2d.mean()

4.111111111111111

In [91]:
## Filtering
npar

array([ 1.,  2.,  4.,  5.,  6.,  7.,  8.,  9.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27.])

In [97]:
npar[(npar>=6) & (npar<=20)]

array([ 6.,  7.,  8.,  9.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19., 20.])

In [99]:
npar[~(npar%2==0)]

array([ 1.,  5.,  7.,  9.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27.])

In [105]:
npar * 2
npar + 2
npar - 2
npar / 2
npar // 2
npar ** 2

array([  1.,   4.,  16.,  25.,  36.,  49.,  64.,  81.,  81., 100., 121.,
       144., 169., 196., 225., 256., 289., 324., 361., 400., 441., 484.,
       529., 576., 625., 676., 729.])

In [110]:
npar * npar
npar + npar
npar - npar
npar / npar

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [116]:
arr2d * arr2d

array([[ 1,  4,  9],
       [16, 25, 49],
       [16, 25, 36]])

In [115]:
arr2d@arr2d

array([[21, 27, 35],
       [52, 68, 89],
       [48, 63, 83]])

In [119]:
np.sin(npar)
np.cos(npar)

array([ 0.54030231, -0.41614684, -0.65364362,  0.28366219,  0.96017029,
        0.75390225, -0.14550003, -0.91113026, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206,
       -0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281,
        0.64691932, -0.29213881])

In [122]:
arr2d

array([[1, 2, 3],
       [4, 5, 7],
       [4, 5, 6]])

In [121]:
np.transpose(arr2d)

array([[1, 4, 4],
       [2, 5, 5],
       [3, 7, 6]])

In [126]:
np.dot(arr2d, arr2d)

array([[21, 27, 35],
       [52, 68, 89],
       [48, 63, 83]])

In [136]:
np.cross(arr2d, arr2d)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [124]:
from numpy import linalg as l
l.det(arr2d)
l.inv(arr2d)

array([[-1.66666667,  1.        , -0.33333333],
       [ 1.33333333, -2.        ,  1.66666667],
       [-0.        ,  1.        , -1.        ]])

In [125]:
l.norm(arr2d)

13.45362404707371

In [130]:
arr2d.T

array([[1, 4, 4],
       [2, 5, 5],
       [3, 7, 6]])

In [135]:
np.linspace(1,10, 50, retstep=True, endpoint=False)

(array([1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
        2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
        4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
        6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
        8.92, 9.1 , 9.28, 9.46, 9.64, 9.82]),
 0.18)

In [148]:
np.meshgrid(np.arange(1,10, 1.5), np.arange(10,20, 1.5))

[array([[1. , 2.5, 4. , 5.5, 7. , 8.5],
        [1. , 2.5, 4. , 5.5, 7. , 8.5],
        [1. , 2.5, 4. , 5.5, 7. , 8.5],
        [1. , 2.5, 4. , 5.5, 7. , 8.5],
        [1. , 2.5, 4. , 5.5, 7. , 8.5],
        [1. , 2.5, 4. , 5.5, 7. , 8.5],
        [1. , 2.5, 4. , 5.5, 7. , 8.5]]),
 array([[10. , 10. , 10. , 10. , 10. , 10. ],
        [11.5, 11.5, 11.5, 11.5, 11.5, 11.5],
        [13. , 13. , 13. , 13. , 13. , 13. ],
        [14.5, 14.5, 14.5, 14.5, 14.5, 14.5],
        [16. , 16. , 16. , 16. , 16. , 16. ],
        [17.5, 17.5, 17.5, 17.5, 17.5, 17.5],
        [19. , 19. , 19. , 19. , 19. , 19. ]])]

In [140]:
np.c_[npar,npar+2]

array([[ 1.,  3.],
       [ 2.,  4.],
       [ 4.,  6.],
       [ 5.,  7.],
       [ 6.,  8.],
       [ 7.,  9.],
       [ 8., 10.],
       [ 9., 11.],
       [ 9., 11.],
       [10., 12.],
       [11., 13.],
       [12., 14.],
       [13., 15.],
       [14., 16.],
       [15., 17.],
       [16., 18.],
       [17., 19.],
       [18., 20.],
       [19., 21.],
       [20., 22.],
       [21., 23.],
       [22., 24.],
       [23., 25.],
       [24., 26.],
       [25., 27.],
       [26., 28.],
       [27., 29.]])

In [143]:
arr2d.ravel()

array([1, 2, 3, 4, 5, 7, 4, 5, 6])

In [146]:
arr2d.argmax()
arr2d.argmin()
arr2d.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [ ]:
np.